parameters:
  statemachine.config: '/app/src/ProcessOrderExample/Configuration/ProcessOrder.json'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Statemachine\:
    resource: '../src/*'
    exclude: '../src/**/{Entity,*ValueObject.php,*Collection.php,app.php}'

  Statemachine\Infrastructure\Json\LoadJsonFromFile:
    class: Statemachine\Infrastructure\Json\LoadJsonFromFile
    arguments: ['%statemachine.config%']

  Statemachine\Statemachine\Command\RunEvent:
    class: Statemachine\Statemachine\Command\RunEvent
    public: true
